### ISSUE TITLE
Move implementation planning into GitHub issues

### ISSUE THREAD

**Issue by haed** [sempods/sempods-kotlin#118]
## Goal

Use GitHub issues as the canonical home for implementation goals, planned iterations, decisions, dependencies and progress. Every delivered change updates its documentation in the same PR. Retire repository roadmap files, the consolidate-roadmap procedure and the mixed SOLL-to-IST concept lifecycle. Private maintainer planning remains outside this migration.

The maintainer requested this workflow change. #105 demonstrates the intended issue-based approach. The specification has its own migration in sempods/sempods-spec#59; both repository migrations can be executed independently.

## Replacement document types

The replacement for the former four types is **Vision, maintained IST documentation, and Proposal**. #119 defines these types and their nesting in documentation-strategy.md and updates every active summary before later content moves.

- **Vision:** vision.md at the repository or justified module scope, expressing long-term direction independently of implementation.
- **Maintained IST documentation:** explanations of current architecture and behavior, at their responsible scope; field-level contracts stay in KDoc. docs/concepts/ remains an organizational folder for useful current architecture explanations, not a fourth type or a special lifecycle. Keep useful documents in place; merge or remove them only where their content is redundant or belongs with an existing owner.
- **Proposal:** occasional substantive proposed design under docs/proposals/ at the appropriate scope, explicitly marked proposed and linked to its issue. It holds reviewable design detail, not task progress. Create it only when actual content warrants it. Its disposition and adoption links remain clear; a merged proposal does not assert implementation.

Future work belongs in issues by default. Existing mixed documents are classified passage by passage in #121; changing their type never makes planned behavior current. AGENTS.md and procedure files remain instruction maps and working rules, outside these three subject-document types.

## Ownership

| Information | Canonical home |
|---|---|
| Long-term direction | Existing vision documents |
| Problem, target, scope, decisions and overall acceptance | Parent issue |
| An independently reviewable iteration and its evidence | Sub-issue and linked PRs |
| Membership and prerequisites | Native parent/sub-issue and blocked-by relationships |
| Current architecture and behavior | Maintained documentation at the responsible module or repository scope; field contracts in KDoc |
| Extensive proposed implementation design, when an issue is insufficient | Explicit proposal document linked from its issue, without a progress checklist |
| Normative protocol requirements | sempods-spec |

Code establishes what this implementation does; the specification establishes what it must satisfy. Moving a plan does not implement it or adopt a protocol proposal.

This explicitly replaces the rules “Tracking issues are optional and hold no state” and “A tracking issue holds no state.” Issues own target, decisions and progress for new or migrated work; only identified repository roadmaps retain temporary authority until their mapping in #120.

A small change may use one standalone issue. A minor local omission may remain a // TODO: at its code location, saying what is missing and why it matters; #119 preserves that rule permanently before #120 retires the old procedure. Parent descriptions hold the current goal and decisions; sub-issues hold work progress. Do not duplicate their state in Markdown checklists. Discussion belongs in comments, with its actionable result incorporated into the owning description. Keep the rationale needed to understand current behavior in maintained documentation when that behavior lands.

## Private planning and source references

Private planning stays private: do not inspect, import or reconstruct its contents. The maintainer has authorized #121 to remove opaque private, ambiguous and historical roadmap references from public documentation and source comments, replacing the preservation exception introduced by #119. Public explanations must stand on their own: retain useful technical rationale and current constraints in their maintained owner, and track actionable work already described publicly in issues. Remove obsolete item numbers; never delete a non-obvious invariant merely to clear a keyword search.

## Iterations

Sequence: #119 → #120 → #121, recorded as native blocked-by dependencies. The native sub-issues define the work breakdown: establish the rules and templates, migrate roadmap tracking, then separate proposed design from current documentation and finish the repository-wide verification. Each step must leave usable instructions and valid links.

New work uses issues. Existing roadmap and SOLL files retain their explicitly bounded authority until the issue that migrates them completes its mapping. Transfer ownership once per source; do not maintain two status lists.

## Completion for every issue

Every implementation PR runs the applicable documentation-sync procedure before review. Update affected IST documents, KDoc, context7.json and pointers in that PR, or record a specific reason that no documentation change is needed. Multi-PR issues apply this rule to every PR; documentation never waits for the final iteration.

Close a sub-issue as completed only when its acceptance criteria are satisfied, its implementation PRs are merged and relevant checks and documentation results are recorded. Link partial PRs without prematurely closing the issue. A proposal issue completes when the stated proposal deliverable is reviewed; it does not assert implementation.

Close this parent after its own acceptance criteria are verified. A closed-as-not-planned child is not delivered scope: explicitly revise the agreed scope or leave the parent open. Document remaining work in linked issues.

## Planning metadata

Reuse existing labels, including documentation and relevant module labels. Use release milestones only for agreed release scope; Kotlin and specification versions remain independent. Git tags identify published revisions.

A shared organization Project may later provide cross-repository views, priority and iteration fields over these same issues. It is optional and does not gate this migration. Avoid parallel status labels or an additional manually maintained plan.

## Acceptance

- New work is discoverable and executable through issues and their PRs.
- Repository and module instructions, contributor forms, tool pointers and documentation indexes agree on issue planning and per-PR documentation.
- All in-scope public planning artifacts and unresolved decisions have a traceable issue or explicit disposition; minor local TODOs follow the rule above and public explanations no longer depend on private-source references. Useful implemented rationale remains maintained.
- No active repository roadmap file or consolidate-roadmap procedure remains. Current documentation does not present proposed behavior as implemented.
- Documentation links and relevant checks pass. No runtime behavior, normative contract, release promise or private/public boundary changes as a side effect.
- The native children have landed and their evidence establishes the overall result.

No release milestone is assumed for this process change. No implementation work from #105 or another feature is included.
